name: Upload Inspections Data to S3

on:
  workflow_dispatch:
  push:
    branches:
      - master
  schedule:
    - cron: '0 17 * * *'  # Runs daily at 12 p.m. EST

permissions:
  actions: write

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies from requirements.txt
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          playwright install --with-deps chromium

      - name: Verify Installed Packages
        run: pip list

      - name: Run scraper and upload to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          S3_FILE_NAME: ${{ secrets.S3_FILE_NAME }}
          GEOCODIO_API_KEY: ${{ secrets.GEOCODIO_API_KEY }}
        run: |
          python -m pip list
          python scraper.py

  keepalive:
    if: github.event_name == 'schedule'
    runs-on: ubuntu-latest
    needs: upload
    steps:
      - uses: actions/checkout@v4
      - uses: gautamkrishnar/keepalive-workflow@v2